### ISSUE TITLE
Hangs forever on 'Updating' this repo.

### ISSUE THREAD

**Issue by pranavgade20** [ethcore/js-precompiled#3]
Hi there!

My computer ran` cargo fetch --manifest-path ./Cargo.toml`, and it stops forever on `Updating git repository https://github.com/paritytech/js-precompiled.git`.
I think this problem may be due to the fact that this repo was moved recently without taking in account this issue.

I hope this issue will be solved soon.
Thanks.

**Comment by tomusdrw** [comment]
This repo is pretty huge, so it takes quite a long time to update it.
I'd suggest updating your any dependencies on this (assuming it's Parity) to the latest version, since we don't use it any more.
